config/routes.rb
require 'resque_web'

Rails.application.routes.draw do
  get '/robots.:format' => 'static_pages#robots'

  namespace :cabinet do
    resources :orders, only: [:show]

    root to: 'orders#index'
  end

  namespace :lk do
    mount ResqueWeb::Engine => "/resque"

    resources :callback_phones, only: :index
    resources :cities, except: [:show]
    resources :congratulations
    resources :galleries, only: [:index, :create, :update, :destroy]
    resources :gift_card_orders, only: :index
    resources :gifts, except: :show
    resources :faqs, except: :show
    resources :letters, only: [:index, :show]
    resources :letter_image_templates
    resources :letter_text_templates
    resources :orders, except: [:new, :create]
    resources :static_data, only: [:index] do
      patch :update, on: :collection
    end
    resources :users, only: [:index]

    root to: 'dashboard#index'
  end

  namespace :api do
    resources :cities, only: [:index] do
      resources :delivery_addresses, only: [:index]
    end
  end

  resources :callback_phones, only: :create

  resources :cities, only: [:create, :show] do
    resources :delivery_addresses, only: [:index]
  end
  resources :gifts, only: :show
  # resources :gift_card_orders, only: :create
  get :catalog, to: 'home#catalog'

  resources :orders, only: [:create]
  get :order, to: 'orders#new'
  resources :users, only: [:create]

  get :napisat_pismo_dedu_morozu_v_velikiy_ustyug_2018, to: 'letters#new'
  post :napisat_pismo_dedu_morozu_v_velikiy_ustyug_2018, to: 'letters#create'

  get 'napisat_pismo_dedu_morozu_v_velikiy_ustyug_2018', to: 'letters#new'
  post 'napisat_pismo_dedu_morozu_v_velikiy_ustyug_2018', to: 'letters#create'

  match :reset_password, to: 'sessions#reset_password', via: [:get, :post]
  get :sign_in, to: 'sessions#sign_in'
  post :sign_in, to: 'sessions#create'
  delete :logout, to: 'sessions#logout'

  root to: 'home#index'
  # root to: 'static_pages#home'
  # get 'thank_for_order', to: 'static_pages#thank_for_order'

  get '*unmatched_route', to: 'application#render_404'
end

app/views/lk/layouts/shared/_navbar.html.slim
nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      button.navbar-toggle[type="button"]
        span.sr-only
          | Toggle navigation
        span.icon-bar.bar1
        span.icon-bar.bar2
        span.icon-bar.bar3
      span.navbar-brand= content_for(:lk_title_page)
    .collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        - if policy(:session).logout?
          li
            = link_to logout_path, method: :delete do
              = t('logout')

app/views/lk/layouts/shared/_sidebar.html.slim
.sidebar[data-background-color="white" data-active-color="danger"]
  .sidebar-wrapper
    .logo
      = link_to t('back_to_site'), root_path, class: 'simple-text'
    ul.nav
      = sidebar_active_link(lk_root_path) do
        i.ti-panel
        p= t('dashboard')

      = sidebar_active_link(lk_static_data_path) do
        i.ti-panel
        p= t('configuration')

      = sidebar_active_link(lk_gifts_path, 'lk/gifts') do
        i.ti-gift
        p= t('gifts')

      = sidebar_active_link(lk_users_path, 'lk/users') do
        i.ti-user
        p= t('users')

      = sidebar_active_link(lk_cities_path, 'lk/cities') do
        i.ti-home
        p= t('cities')
      = sidebar_active_link(lk_orders_path, 'lk/orders') do
        i.ti-clipboard
        p= t('orders')

      = sidebar_active_link(lk_gift_card_orders_path, 'lk/gift_card_orders') do
        i.ti-clipboard
        p= t('gift_card_orders')

      = sidebar_active_link(lk_callback_phones_path, 'lk/callback_phones') do
        i.ti-mobile
        p= t('callback_phones')

      = sidebar_active_link(lk_faqs_path, 'lk/faqs') do
        i.ti-help-alt
        p= t('faqs')

      = sidebar_active_link(lk_galleries_path, 'lk/galleries') do
        i.ti-gallery
        p= t('galleries')

    hr
    h5.logo = t('letter_generator')
    ul.nav
      = sidebar_active_link(lk_letter_image_templates_path, 'lk/letter_image_templates') do
        i.ti-gallery
        p= t('letter_image_templates')

      = sidebar_active_link(lk_letter_text_templates_path, 'lk/letter_text_templates') do
        i.ti-write
        p= t('letter_text_templates')

      = sidebar_active_link(lk_congratulations_path, 'lk/congratulations') do
        i.ti-layout-placeholder
        p= t('congratulations')

    hr
    h5.logo = t('ded_moroz_letters')
    ul.nav
      = sidebar_active_link(lk_letters_path, 'lk/letters') do
        i.ti-layout-placeholder
        p= t('letters')