config/routes.rb
require 'resque_web'

Rails.application.routes.draw do
  get '/robots.:format' => 'static_pages#robots'

  namespace :cabinet do
    resources :orders, only: [:show]

    root to: 'orders#index'
  end

  namespace :lk do
    mount ResqueWeb::Engine => "/resque"

    resources :callback_phones, only: :index
    resources :cities, except: [:show]
    resources :congratulations
    resources :galleries, only: [:index, :create, :update, :destroy]
    resources :gift_card_orders, only: :index
    resources :gifts, except: :show
    resources :faqs, except: :show
    resources :letters, only: [:index, :show]
    resources :letter_image_templates
    resources :letter_text_templates
    resources :orders, except: [:new, :create]
    resources :static_data, only: [:index] do
      patch :update, on: :collection
    end
    resources :users, only: [:index]

    root to: 'dashboard#index'
  end

  namespace :api do
    resources :cities, only: [:index] do
      resources :delivery_addresses, only: [:index]
    end
  end

  resources :callback_phones, only: :create

  resources :cities, only: [:create, :show] do
    resources :delivery_addresses, only: [:index]
  end
  resources :gifts, only: :show
  # resources :gift_card_orders, only: :create
  get :catalog, to: 'home#catalog'

  resources :orders, only: [:create]
  get :order, to: 'orders#new'
  resources :users, only: [:create]

  get :napisat_pismo_dedu_morozu_v_velikiy_ustyug_2018, to: 'letters#new'
  post :napisat_pismo_dedu_morozu_v_velikiy_ustyug_2018, to: 'letters#create'

  get 'napisat_pismo_dedu_morozu_v_velikiy_ustyug_2018', to: 'letters#new'
  post 'napisat_pismo_dedu_morozu_v_velikiy_ustyug_2018', to: 'letters#create'

  match :reset_password, to: 'sessions#reset_password', via: [:get, :post]
  get :sign_in, to: 'sessions#sign_in'
  post :sign_in, to: 'sessions#create'
  delete :logout, to: 'sessions#logout'

  root to: 'home#index'
  # root to: 'static_pages#home'
  # get 'thank_for_order', to: 'static_pages#thank_for_order'

  get '*unmatched_route', to: 'application#render_404'
end

app/views/layouts/shared/_footer.html.slim
section
  section.footer
  .footer-bg
    .container
      .footer-content
        .footer-contacts
          a.footer-phone[href="tel:+74951251069"]
            | МСК: +7(495) 125-10-69
          a.footer-phone[href="tel:+79119242163"]
            | СПб: +7(911) 924-21-63
          .footer-cconfidentially
            | © f121.ru 2012
        .footer-socials
          a.footer-social[href="https://vk.com/pismo_ot_deda_moroza7"]
            = image_tag("social/vk.png")
          a.footer-social[href=""]
            = image_tag("social/ok.png")
          a.footer-social[href=""]
            = image_tag("social/fb.png")
          a.footer-social[href=""]
            = image_tag("social/inst.png")
          a.footer-social[href=""]
            = image_tag("social/you.png")
          .footer-email
            | info@f121.ru

app/views/layouts/shared/_navbar.html.slim
section#main-land.main
  .container
    header.nav-bar
      .nav-bar__menu
        a.hamb[href="javascript:void(0);"]
          span.hamb-box
            span.hamb-inner
        nav.nav-container
          ul
            li
              a.class_nav[href="#main-land"]
                | Главная
            li
              a.class_nav[href=""]
                | Доставка
            li
              a.class_nav[href="#cost-scroll"]
                | Оплата
            li
              a.class_nav[href="#gifts-scroll"]
                | Подарки
            li
              a.class_nav[href="#faq-scroll"]
                | FAQ
            li
              a.class_nav[href="#order-scroll"]
                | Заказать
            - if policy(:session).signed_in?
              li= link_to t('cabinet'), cabinet_root_path
            - if policy(:admin_session).current_user_is_admin?
              li= link_to t('dashboard'), lk_root_path
            - if policy(:session).sign_in?
              li= link_to t('sign_in'), sign_in_path
            - if policy(:session).logout?
              li= link_to t('logout'), logout_path, method: :delete
      .nav-bar__phone
        a.header-phone[href="tel:+74951251069"]
          | МСК: +7(495) 125-10-69
        a.header-phone[href="tel:+79119242163"]
          | СПб: +7(911) 924-21-63
    - if controller_path == 'home' && action_name == 'index'
      .main-content
        .content-50
          = image_tag('main/girl-first.png', class: 'main-first__girl')
        .content-50
          h1.main-titel
            |  Письмо от Деда Мороза с сургутной печатью
          span.main-text
            | Сделайте новогоднюю ночь 2017 незабываемой, оставив на память необыновенный подарок!
          .main-last
            = link_to 'Заказать письмо', new_order_path, class: 'btn-order__first'
            span.main-price
              | 390 руб.