config/routes.rb
require 'resque_web'

Rails.application.routes.draw do
  get '/robots.:format' => 'static_pages#robots'

  namespace :cabinet do
    resources :orders, only: [:show]

    root to: 'orders#index'
  end

  namespace :lk do
    mount ResqueWeb::Engine => "/resque"

    resources :callback_phones, only: :index
    resources :cities, except: [:show]
    resources :congratulations
    resources :galleries, only: [:index, :create, :update, :destroy]
    resources :gift_card_orders, only: :index
    resources :gifts, except: :show
    resources :faqs, except: :show
    resources :letters, only: [:index, :show]
    resources :letter_image_templates
    resources :letter_text_templates
    resources :orders, except: [:new, :create]
    resources :static_data, only: [:index] do
      patch :update, on: :collection
    end
    resources :users, only: [:index]

    root to: 'dashboard#index'
  end

  namespace :api do
    resources :cities, only: [:index] do
      resources :delivery_addresses, only: [:index]
    end
  end

  resources :callback_phones, only: :create

  resources :cities, only: [:create, :show] do
    resources :delivery_addresses, only: [:index]
  end
  resources :gifts, only: :show
  # resources :gift_card_orders, only: :create
  get :catalog, to: 'home#catalog'

  resources :orders, only: [:create]
  get :order, to: 'orders#new'
  resources :users, only: [:create]

  get :napisat_pismo_dedu_morozu_v_velikiy_ustyug_2018, to: 'letters#new'
  post :napisat_pismo_dedu_morozu_v_velikiy_ustyug_2018, to: 'letters#create'

  get 'napisat_pismo_dedu_morozu_v_velikiy_ustyug_2018', to: 'letters#new'
  post 'napisat_pismo_dedu_morozu_v_velikiy_ustyug_2018', to: 'letters#create'

  match :reset_password, to: 'sessions#reset_password', via: [:get, :post]
  get :sign_in, to: 'sessions#sign_in'
  post :sign_in, to: 'sessions#create'
  delete :logout, to: 'sessions#logout'

  root to: 'home#index'
  # root to: 'static_pages#home'
  # get 'thank_for_order', to: 'static_pages#thank_for_order'

  get '*unmatched_route', to: 'application#render_404'
end

app/views/layouts/santa_1_0/shared/_footer.html.slim
section
  section.footer
  .footer-bg
    .container
      .footer-content
        .footer-contacts
          a.footer-phone[href="tel:+74951251069"]
            | МСК: #{StaticData.msk_phone}
          a.footer-phone[href="tel:+79119242163"]
            | СПБ: #{StaticData.spb_phone}

          .footer-cconfidentially
            | © f121.ru &nbsp 2012 - #{Date.today.year + 1}
        .footer-socials
          .ics
            a.footer-social[href="https://vk.com/pismo_ot_deda_moroza7" target="_blank"]
              = image_tag("img/social/vk.png", alt: "Социальная сеть")
            a.footer-social[href="https://ok.ru/group/53392279929017" target="_blank"]
              = image_tag("img/social/ok.png", alt: "Социальная сеть")
            a.footer-social[href="https://www.facebook.com/dedmorozpismo/" target="_blank"]
              = image_tag("img/social/fb.png", alt: "Социальная сеть")
            a.footer-social[href="https://www.instagram.com/pismo_dm/" target="_blank"]
              = image_tag("img/social/inst.png", alt: "Социальная сеть")
            a.footer-social[href="https://www.youtube.com/watch?v=8mWSWTiM0E8&feature=youtu.be"]
              = image_tag("img/social/you.png", alt: "Социальная сеть")
          .footer-email
            | #{StaticData.email}

app/views/layouts/santa_1_0/shared/_navbar.html.erb
<section class="nav-bar__web">
      <div class="nav-bar__menu">
        <a class="hamb" href="javascript:void(0);">
          <span class="hamb-box">
            <span class="hamb-inner"></span>
          </span>
        </a>
        <div class="fixe-container">
          <nav class="nav-container">
            <ul>
              <li><%= link_to 'Главная', root_path(anchor: 'main-land'), class: 'class_nav' %></li>
              <li><%= link_to 'Подарки', root_path(anchor: 'gifts-scroll'), class: 'class_nav' %></li>
              <li><%= link_to 'FAQ', root_path(anchor: 'faq-scroll'), class: 'class_nav' %></li>
              <li><%= link_to 'Оплата', root_path(anchor: 'issues-pay__methods'), class: 'class_nav' %></li>
              <li><%= link_to 'Доставка', root_path(anchor: 'transfer'), class: 'class_nav' %></li>
              <li><%= link_to 'Заказать', order_path %></li>
              <% if policy(:session).signed_in? %>
                <li><%= link_to t('cabinet'), cabinet_root_path %></li>
              <% end %>
              <% if policy(:admin_session).current_user_is_admin? %>
                <li><%= link_to t('dashboard'), lk_root_path %></li>
              <% end %>
              <% if policy(:session).sign_in? %>
                <li><%= link_to t('sign_in'), sign_in_path %></li>
              <% end %>
              <% if policy(:session).logout? %>
                <li><%= link_to t('logout'), logout_path, method: :delete %></li>
              <% end %>
            </ul>
          </nav>
          <div class="left-block"></div>
        </div>
      </div>
    </section>